# Default configuration
app:
  watched_folder: "interactive_video_booth/outputs"
  output_width: 1920
  output_height: 1080
  fps: 30
  record_duration_s: 10
  gpu: false

cameras:
  primary_camera_id: 0
  secondary_camera_id: null  # set to an integer index or RTSP URL

fusion:
  seg_weight: 0.6
  motion_weight: 0.4
  on_threshold: 0.4
  off_threshold: 0.2
  persistence_frames: 10

render:
  fullscreen: true
  window_name: "Silhouette Booth"
  effect: "glow"  # glow | density | trails
